### ISSUE TITLE
mac端

### ISSUE THREAD

**Issue by dawnadvent** [tlslink/sslcon#2]
什么时候考虑出mac版本呢？谢谢

**Comment by itviewer** [comment]
这得看什么时候考虑入手一台mac笔记本

**Comment by yourenyouyu** [comment]
大佬，mac端怎么运行，tun创建成功读取失败，看你这边wireguard代码好像改了

**Comment by yourenyouyu** [comment]
执行到这里爆错
go tunToPayloadOut(dev, cSess) // read from apps
go payloadInToTun(dev, cSess)  // write to apps

**Comment by itviewer** [comment]
> 大佬，mac端怎么运行，tun创建成功读取失败，看你这边wireguard代码好像改了

你自己看着把wireguard的代码复制过来，tun创建成功后需要配置好ip
需要增加移植的文件包括tun目录和utils目录，

tun目录应该直接复制wg的文件即可，utils目录需要移植下ip和路由设置命令，建议参考
cd1368a3a27ef738d43ec4add7be9befba26a8f5 这个提交之前的 utils_linux.go 文件，通过第三方命令实现。mac应该是把ip命令换成ifconfig，这个应该比较容易
我没有mac环境，你可以试着弄弄，有错误贴出来

**Comment by yourenyouyu** [comment]
好的 我研究下看看 有问题请教你&nbsp;


鱿刃有鱼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XinJun ***@***.***&gt;; 
发送时间: 2023年8月20日(星期天) 凌晨2:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tlslink/vpnagent] mac端 (Issue #2)





  
大佬，mac端怎么运行，tun创建成功读取失败，看你这边wireguard代码好像改了
  
你自己看着把wireguard的代码复制过来，tun创建成功后需要配置好ip
 需要增加移植的文件包括tun目录和utils目录，
 
tun目录应该直接复制wg的文件即可，utils目录需要移植下ip和路由设置命令，建议参考
 cd1368a 这个提交之前的 utils_linux.go 文件，通过第三方命令实现。mac应该是把ip命令换成ifconfig，这个应该比较容易
 我没有mac环境，你可以试着弄弄，有错误贴出来

**Comment by yourenyouyu** [comment]
<img width="685" alt="image" src="https://github.com/tlslink/vpnagent/assets/13463500/adb1d23f-92f0-4cfa-990b-517f843ad2ac">
网卡创建成功，但是访问服务的时候出现这个 @itviewer

**Comment by itviewer** [comment]
抱歉，最近没时间搞这个，需要移植的地方大概就那两个目录，
- 建tun 设备
- 配置tun设备ip和路由

项目本身也没多少代码，相关注释也有，建议一边查看协议文档，一边在Linux下一行一行的去调试，在Linux下搞明白了整个流程再去移植

**Comment by itviewer** [comment]
tun设备创建的代码从wg复制过来后，看情况是否需要修改，我没设备没法调试，但大概率不需要修改。主要问题是在mac下实现这个函数
utils.ConfigInterface 以及相关的系统路由设置

**Comment by yourenyouyu** [comment]
好的 我研究下哈，谢谢啦

**Comment by yourenyouyu** [comment]
@itviewer 您好，方便加个微信请教下么

**Comment by levinit** [comment]
是不是只支持win

**Comment by itviewer** [comment]
macos 目前已经可以使用，[安装说明](https://github.com/tlslink/anylink-client?tab=readme-ov-file#macos)
我自己目前使用会出现断线重连问题，不确定是我自己服务器问题还是客户端软件问题，有兴趣的话可以帮忙测试一下。
使用一段时间后看下 关于-查看连接日志
